### ISSUE TITLE
NewlineProcessingFilter whitespace handling

### ISSUE THREAD

**Issue by mattmassicotte** [ChimeHQ/TextFormation#4]
From https://github.com/CodeEditApp/CodeEditTextView/pull/135, it sounds like there could be a problem with how `NewlineProcessingFilter` handles whitespace. I'm not sure how it could be that I haven't noticed this before. But, this stuff is all tricky, and whitespace/indentation in particular can be really tough.

**Comment by mattmassicotte** [comment]
Comment from @thecoolwinter:

For some reason it's recognizing the beginning of the previous line as the end of the line, but only every other newline. I found that removing the line ending logic fixed it temporarily.

**Comment by thecoolwinter** [comment]
Here's the behavior I was trying to describe. On every other newline it deletes the previous line and adds the next line.

https://user-images.githubusercontent.com/35942988/215349789-26afff5a-298e-439c-93f2-5a1b3b68890a.mov

**Comment by mattmassicotte** [comment]
Thank you for the video! At first, I was really struggling to capture this behavior in a test. But, I then realized that the stupid tests use "lll" (leading) and "ttt" (trailing) as their whitespace. However, these characters aren't actually whitespace, and that really matters 😵

So, with that realization, I can reproduce the problem. As for why I never noticed this - hard to say. Probably because Chime's internal indentation computation system is affecting this. It only uses TextFormation's indentation as a fallback.

**Comment by mattmassicotte** [comment]
Well, looking into this has proven to be fascinating. `NewlineProcessingFilter` needs leading whitespace for indentation. But, the reason it needs trailing was really just to trim it. (Quick aside: this **must** happen here because only one filter can change text for a given mutation).

But now that I've realized this, there's really no need for so general a system. I think this can be fixed and also is motivating me to just simplify the entire system to not need a trailing whitespace provider. I'm into making this change, but it's complex. So, I'm goin to work on fixing this first, and then investigate the next bit later.

But, I really appreciate you finding this, as it's a pretty serious problem.

**Comment by thecoolwinter** [comment]
Wait, I'm still a little confused what it's doing? It seems to work perfectly without it and I couldn't find an edge case where it didn't.

**Comment by mattmassicotte** [comment]
The code you removed handles **trailing** whitespace, not leading (indentation). Consider this:

```
abc\t
```

output:

```
abc\n

```


On return, you may want to trim that trailing `\t`. I'd still like this behavior, but I have a bit of work to do to restore that while also correcting this issue you found.

**Comment by thecoolwinter** [comment]
Ah I see, it might be easier to do the trimming before the newline then. So it could just be a delete all previous whitespace (if there's any non-whitespace characters). Then the operation would go:
```
abc\t <- newline entered

abc <- remove previous whitespace

abc\n <- add newline & indentation if needed
```

And then making sure to add a check if the trimming is needed would be good so it doesn't cause something like this.
```
\t\tabc
\t\t <- newline entered

\t\tabc
 <- remove whitespace (wrong)

\t\tabc

\t\t <- add newline + tabs
```

**Comment by mattmassicotte** [comment]
I have to look into it more. Changing text before the incoming mutation makes its range invalid. Sometimes this is no big deal, but sometimes it's a pain. I now remember, too, why this has to be deferred to the client as a function - whitespace trimming behavior can be a user pref.

**Comment by thecoolwinter** [comment]
Ah, I'm beginning to see the complexity of the problem after trying it a little more myself. Thanks for being willing to check it out!

**Comment by mattmassicotte** [comment]
I think https://github.com/ChimeHQ/TextFormation/commit/d2b7f61ff747dab863290a2d50b9fbbdc7b91413 will help to address this. However, I'm a little worried about the interaction with your `DeleteWhitespaceFilter`. So, @thecoolwinter I'd really appreciate you trying out this out and letting me know.

**Comment by thecoolwinter** [comment]
Looks like it works perfectly fine! 👍

**Comment by thecoolwinter** [comment]
Looks like it works fine the the `DeleteWhitespaceFilter`, the only issue I see now is that `STTextView` handles selection locations like iOS so when the trailing method is triggered it stays on the previous line. Is there any reason for leaving lines 55-65 in a conditional? Besides different behaviors on iOS vs macOS, it wouldn't necessarily break on macOS if it used the iOS insertion everywhere would it?

**Comment by mattmassicotte** [comment]
@thecoolwinter you know, I was trying to achieve good multiple selection behavior on macOS. But, I can already see that this isn't going to work well in that case anyways. The whole concept of of a single "insertionLocation" doesn't make sense there.

I think what you suggest is good, but I would love to revisit this to better support multiple selection, because NSTextView already supports it quite well. That is going to require a revision to the `TextInterface` protocol, which is going to be a pain.

**Comment by mattmassicotte** [comment]
Ok, that's done. You want to give latest main one more try?

**Comment by thecoolwinter** [comment]
Looks like it work's perfectly! (sorry for the late response) Are you planning to make a release for this or should we just use `main` for now.

**Comment by mattmassicotte** [comment]
Fantastic! I was just waiting for your confirmation. Going to do a bit more testing on my end and then I'll do a new release.

**Comment by mattmassicotte** [comment]
https://github.com/ChimeHQ/TextFormation/releases/tag/0.6.8

Thanks so much @thecoolwinter for all your help with this.
