### ISSUE TITLE
VisionOS fails to compile

### ISSUE THREAD

**Issue by crabtree-michael** [ChimeHQ/TextFormation#7]
VisionOS currently fails to build. I tried putting up a pull request to fix the issue, but was denied access to push the branch. I'm attaching the diff that fixed it.

[diff.txt](https://github.com/ChimeHQ/TextFormation/files/14469383/diff.txt)

**Comment by mattmassicotte** [comment]
Ah shoot. Thank you for finding this!

Yes, you must fork, change in your copy and open a PR. Is that something you'd like to do? It will give you contribution credit. But, I can also take care of this myself.

**Comment by mattmassicotte** [comment]
(also super weird that SPI visionOS builds succeed...)

**Comment by crabtree-michael** [comment]
> Ah shoot. Thank you for finding this!
> 
> Yes, you must fork, change in your copy and open a PR. Is that something you'd like to do? It will give you contribution credit. But, I can also take care of this myself.

That's ok seems like a lot of work for such a small change 😅 If I make a larger contribution, I'll do it.

**Comment by mattmassicotte** [comment]
Figured out why SPI thinks this can build: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2923

**Comment by crabtree-michael** [comment]
Thanks for fixing this Matt.

**Comment by mattmassicotte** [comment]
You got it! It turned out to be a pretty serious issue with SPI, so it's extra-great you reported it. I really appreciate it! And if you have any additional questions about this repo, I'd love to hear them!
